services:
  db:
    image: postgres:latest
    container_name: timing-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: timing
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: timing-be
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./logs:/logs
    ports:
      - "8080:8080"

volumes:
  db_data: